apiVersion: v1
kind: Service
metadata:
  name: funceasy-mysql
  namespace: funceasy
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: funceasy-mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: funceasy
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: funceasy
  name: funceasy-mysql
spec:
  selector:
    matchLabels:
      app: funceasy-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: funceasy-mysql
    spec:
      containers:
        - image: ziqiancheng/funceasy-mysql
          name: funceasy-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "administrator"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim